[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Safelist public client-side env keys that appear in the bundle
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL"
